language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codecov
script: python manage.py test
after_success:
  - codecov -t 02c861c6-631b-40b5-adb8-4dd52d2e9689
